from datetime import datetime
from pathlib import Path
from typing import Optional

def save_travel_plan(response_text: str, directory: str = "./output") -> Optional[str]:
    """
    Export travel plan to Markdown file with proper formatting.
    
    Args:
        response_text (str): The AI-generated travel plan content
        directory (str): Directory to save the file (default: "./output")
    
    Returns:
        str: Path to the saved file, or None if error occurred
    
    Example:
        >>> save_travel_plan("Day 1: Visit Bali...", "./my_trips")
        './my_trips/AI_Trip_Planner_2024-01-15_14-30-45.md'
    """
    # Create directory if it doesn't exist
    Path(directory).mkdir(parents=True, exist_ok=True)

    # Take the time 
    current_time = datetime.now()
    
    # Format the markdown content
    markdown_content = f"""# ✈️ AI Travel Plan

**Generated:** {current_time.strftime('%Y-%m-%d at %H:%M')}  
**Created by:** Atriyo's Travel Agent

---

{response_text}

---

> ⚡ **Note:** This travel plan was generated by AI.  
> Please verify all information (prices, operating hours, travel requirements) before your trip.

---
*Saved on: {current_time.strftime('%B %d, %Y')}*
"""
    
    try:
        # Generate unique filename with timestamp
        timestamp = current_time.strftime("%Y-%m-%d_%H-%M-%S")
        filename = Path(directory) / f"AI_Trip_Planner_{timestamp}.md"
        
        # Write to file with UTF-8 encoding
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
                
        print(f"✅ Travel plan saved successfully!")
        print(f"📁 Location: {filename.absolute()}")
        return str(filename)
        
    except Exception as e:
        print(f"❌ Error saving markdown file: {e}")
        return None


# Optional: Add functionality to read saved files.
def load_travel_plan(filepath: str) -> str:
    """
    Load a saved travel plan from markdown file.
    
    Args:
        filepath (str): Path to the markdown file
        
    Returns:
        str: Content of the file, or None if error
    """
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return f.read()
    except Exception as e:
        print(f"❌ Error loading file: {e}")
        return None


# Optional: Add functionality to list all travel plans.
def list_travel_plans(directory: str = "./output") -> list:
    """
    List all saved travel plans in the directory.
    
    Args:
        directory (str): Directory to search for travel plans
        
    Returns:
        list: List of file paths, sorted by creation time (newest first)
    """
    try:
        path = Path(directory)
        files = list(path.glob("AI_Trip_Planner_*.md"))
        # Sort by modification time (newest first)
        files.sort(key=lambda x: x.stat().st_mtime, reverse=True)
        return [str(f) for f in files]
    except Exception as e:
        print(f"❌ Error listing files: {e}")
        return []